[package]
name = "sanitizer"
description = "A collection of methods and macros to sanitize struct fields"
keywords = ["sanitizer", "validate", "trim", "e164", "case"]
categories = ["text-processing", "value-formatting"]
version = "0.1.1"
authors = ["weegee <dakshupadhyay991@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
Inflector = "0.11.4"
phonenumber = "0.3.1+8.12.9"
paste = "1.0"
num-traits = "0.2"

[dependencies.sanitizer_macros]
path = "sanitizer-macros"
version = "0.1"
optional = true

[features]
default = [ "derive" ]
derive = [ "sanitizer_macros" ]

[workspace]
members = [ "sanitizer-macros" ]
