[package]
name = "sanitizer_macros"
version = "0.1.2"
edition = "2018"
authors = ["weegee <dakshupadhyay991@gmail.com>"]
license = "MIT"
description = "Derive macro for the sanitizer crate"
keywords = ["sanitizer-macro", "macro"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"

# For macro testing
[dev-dependencies]
sanitizer = { path = "../../sanitizer" }
