name: Rust

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run fmt tests
      run: cargo fmt -- --check
    - name: Run tests for sanitizer_macros
      run: cargo test --verbose --no-fail-fast -p sanitizer_macros
    - name: Run tests for the sanitizer project
      run: cargo test --verbose --no-fail-fast
    - name: Run clippy
      run: cargo check
